# PyBud video logger default config
## Debugger variable display settings

# The names of variables you wish to mute in the PyBud video output
muted-variables:
  - muted_variable_name  # The name of the variable

# Relationships between pointers and lists
pointers:
  - friends: i  # Format: 'list: i', where 'i' is a pointer into 'list'
  - numbers: j

## Rendering

# Number of step frames per second
fps: 2

# The resolution of the base rendering, in pixels
# Note: aspect ratio must match output resolution aspect ratio to prevent stretching
render-resolution:
  width: 1920
  height: 1080
divider-width: 1

# The desired resolution of the video output, in pixels
# If using aspect ratio other than 16:9, change render resolution so that
# the render aspect ratio matches the output aspect ratio
output-resolution:
  width: 1280
  height: 720

font:
  # Supported fonts are in the fonts directory
  font-family: Consolas.ttf
  font-size: 22

intro:
  # Leave empty if you don't want to display an intro screen
  text: "Demo"
  # In seconds
  time: 2
  font-family: Manrope-Bold.otf
  font-size: 60
  color: "#FFFFFF"

# Display "Generated with PyBud" watermark
watermark: yes
